build_dependencies:
  - freetds-devel
  - libaio
dependencies:
  - libaio
targets:
  centos-8:
before_precompile: packaging/before_precompile
after_install: packaging/post_install
after:
  - rm -rf vendor/bundle/ruby/2.2.0/gems/rb-fsevent-0.9.5/spec
