class ModifyBankRefInInw < ActiveRecord::Migration[7.0]
  def up
    #change_column :inward_remittances, :bank_ref, :string, :limit => 50, :comment => 'the reference number generated by the bank'
  end

  def down
    #change_column :inward_remittances, :bank_ref, :string, :limit => 30, :comment => 'the reference number generated by the bank'
  end
end
