class CreateImtTransfers < ActiveRecord::Migration
  def change
    create_table :imt_transfers do |t|
      t.string :imt_ref_no, :limit => 25, :null => false, :comment => "the reference number generated by IMT"
      t.string :status_code, :limit => 25, :null => false, :comment => "the status of the transfer"
      t.string :customer_id, :null => false, :limit => 50, :comment => "the unique no of the customer"
      t.string :bene_mobile_no, :null => false, :limit => 50, :comment => "the mobile no of the beneficiary"
      t.decimal :transfer_amount, :null => false, :comment => "the transfer amount"
      t.string :rmtr_to_bene_note, :null => false, :limit => 255, :comment => "the friendly note from the remitter to the beneficiary"
      t.date :expiry_date
      t.datetime :initiated_at
      t.string :initiation_ref_no, :null => false, :limit => 64
      t.datetime :completed_at
      t.string :acquiring_bank, :limit => 255
      t.datetime :cancelled_at
      t.string :cancellation_ref_no, :limit => 64
      t.datetime :expired_at
    end
  end
end
