class ChangeColumnsInSmPayments < ActiveRecord::Migration
  def change
    remove_index :sm_payments, :name => 'sm_payments_01'
    add_column :sm_payments, :cbs_req_ref_no, :string, :limit => 100, :comment => 'the unique request number for the flex request which is generated by the ESB'
    add_index "sm_payments", ["partner_code", "req_no", "attempt_no", "customer_id"], name: "sm_payments_01", unique: true
    change_column :sm_payments, :rep_no, :string, :limit => 50, :comment => "the unique response no sent by API"
    add_column :sm_payments, :reconciled_at, :datetime, :comment => "the SYSDATE when the transaction was reconciled"
  end
end
