class CreateImtTransfers < ActiveRecord::Migration
  def change
    create_table :imt_transfers, {:sequence_start_value => '1 cache 20 order increment by 1'} do |t|
      t.string :imt_ref_no, :limit => 35, :null => false, :comment => "the reference number generated by IMT"
      t.string :status_code, :limit => 25, :null => false, :comment => "the status of the transfer"
      t.string :customer_id, :null => false, :limit => 50, :comment => "the unique no of the customer"
      t.string :bene_mobile_no, :null => false, :limit => 50, :comment => "the mobile no of the beneficiary"
      t.number :transfer_amount, :null => false, :comment => "the transfer amount"
      t.string :rmtr_to_bene_note, :null => false, :limit => 255, :comment => "the friendly note from the remitter to the beneficiary"
      t.date :expiry_date, :comment => "the expiry date, computed for this transfer"
      t.datetime :initiated_at, :comment => "the date on which the transfer was initiated"
      t.string :initiation_ref_no, :null => false, :limit => 64, :comment => "the unique reference no of the initiate_transfer operation"
      t.datetime :completed_at, :comment => "the date on which the transfer was completed"
      t.string :acquiring_bank, :limit => 255, :comment => "the bank at which the transfer was completed"
      t.datetime :cancelled_at, :comment => "the date on which the transfer was cancelled"
      t.string :cancellation_ref_no, :limit => 64, :comment => "the unique reference no of the cancel_transfer operation"
      t.datetime :expired_at, :comment => "the date on which the transfer expired, this is updated only on confirmation of the expiry from IMT"
      t.string :cancel_reason, :limit => 255, :comment => "the reason to cancel the transfer"
    end
  end
end
